

#ifndef LEDS_REVERSE_MOVEMENT_DIRECTION_H_
#define LEDS_REVERSE_MOVEMENT_DIRECTION_H_

#define LEDS_PORT PA
#define BUTTON_FORWARD PIND2
#define BUTTON_BACKWARD PIND3

#define LAST_LAMP 128
#define FIRST_LAMP 1

#define DELAY_VALUE_INMS 250

void LEDS_REVERSE_MOVEMENT_DIRECTION_Init (void);
void LEDS_REVERSE_MOVEMENT_DIRECTION_Run (void);



#endif